---
title: ""
sidebar: false
---

# STAT 155: Introduction to Statistical Modeling

Macalester College, Fall 2025

::: {style="font-size: 20px;"}
Learn the fundamentals of summarizing, visualizing, and modeling data to answer research questions.
:::

<br>

**Instructor:** [Jedidiah Carlson](https://jedidiahcarlson.com) <br> **Class meeting times:**

-   **Section 05**: Tu/Th 9:40-11:10am

**Class location:** THTR 202 <br>

**Jed's drop-in hours:**

-   **location**: My office (OLRI 236)
-   **times**: See [this calendar](https://calendar.google.com/calendar/u/1?cid=Y19mODU5MTcxYTdjYzUwNWFkMDE1MjVmZGRlMWMwZWFmNDQwZTVlMjk3MDEzNzdhNjQwNDdjNjIyOWY5ZWI4N2E4QGdyb3VwLmNhbGVuZGFyLmdvb2dsZS5jb20).

# Essential Links

| [Syllabus](syllabus.qmd) | [Homework Policies](https://docs.google.com/document/d/1r8URNncf5zv33Bcis-XNjdf2LK9OiMngukgpnpDqcq0/edit?usp=sharing) |
|----|----|
| [**Moodle**](https://moodle.macalester.edu/course/view.php?id=6316) | [**Installing R/RStudio**](tech_setup.qmd) |

------------------------------------------------------------------------

[**STAT 155 Preceptor Office Hours:**]{.underline} There is a link to a Google Calendar containing *all* preceptor office hours available at the top of the course Moodle page!

------------------------------------------------------------------------

## Schedule

The **Topic** column will contain a link to today's activity (to follow along on the screen), and the **.qmd template** column contains a link to download a .qmd file where you can work on the exercises.

-   Details for the current week will be filled in throughout the semester. Any urgent announcements will be made over email.

-   Project-related due dates are not yet in the schedule.

-   Details are subject to change (with plenty of advance warning).

-   Unless specified otherwise:

    -   Moodle Checkpoints (CPs) are due 10 minutes before class.

    -   Practice problems (PPs) are due on Moodle by 11:59pm on the due date.

+----------------------------------------+--------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------+
| **Date**                               | **Topic**                                                                            | **.qmd template**                                                                                    | **Due**                                                                                                                                           |
+----------------------------------------+--------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------+
| **Unit 1: Simple Linear Regression**   |                                                                                      |                                                                                                      |                                                                                                                                                   |
+----------------------------------------+--------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------+
| 9/2                                    | [Welcome](activities/L01-foundations-welcome.qmd)                                    | [01-foundations-welcome-notes.qmd](template_qmds/01-foundations-welcome-notes.qmd)                   | Before class:                                                                                                                                     |
|                                        |                                                                                      |                                                                                                      |                                                                                                                                                   |
|                                        |                                                                                      |                                                                                                      | -   Review the [course syllabus](syllabus.qmd)                                                                                                    |
|                                        |                                                                                      |                                                                                                      | -   Familiarize yourself with Moodle and the course website                                                                                       |
|                                        |                                                                                      |                                                                                                      | -   Complete the [Introductions survey](https://forms.gle/y5gBRYimGjR4uzce8)                                                                      |
|                                        |                                                                                      |                                                                                                      | -   [Download R and RStudio](tech_setup.qmd)                                                                                                      |
+----------------------------------------+--------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------+
| 9/4                                    | [Univariate visual & numerical summaries](activities/L02-foundations-univariate.qmd) | [02-foundations-univariate-notes.qmd](template_qmds/02-foundations-univariate-notes.qmd)             | Before class:                                                                                                                                     |
|                                        |                                                                                      |                                                                                                      |                                                                                                                                                   |
|                                        |                                                                                      |                                                                                                      | -   [CP 1](https://moodle.macalester.edu/mod/quiz/view.php?id=220406)                                                                             |
+----------------------------------------+--------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------+
| 9/9                                    | [Intro to simple linear regression](activities/L03-slr-introduction.qmd)             | [03-slr-introduction-notes.qmd](template_qmds/03-slr-introduction-notes.qmd)                         | Before class:                                                                                                                                     |
|                                        |                                                                                      |                                                                                                      |                                                                                                                                                   |
|                                        |                                                                                      |                                                                                                      | -   [CP 2](https://moodle.macalester.edu/mod/quiz/view.php?id=208941)                                                                             |
+----------------------------------------+--------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------+
| 9/11                                   | [simple linear regression: formalization](activities/L04-slr-formalization.qmd)      | [04-slr-formalization-notes.qmd](template_qmds/04-slr-formalization-notes.qmd)                       | PP 1, [CP 3](https://moodle.macalester.edu/mod/quiz/view.php?id=208942)                                                                           |
+----------------------------------------+--------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------+
| 9/16                                   | [Model evaluation](activities/L05-slr-model-eval.qmd)                                | [05-slr-model-eval-notes.qmd](template_qmds/05-slr-model-eval-notes.qmd)                             | [CP 4](https://moodle.macalester.edu/mod/quiz/view.php?id=208943) (optional!)                                                                     |
+----------------------------------------+--------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------+
| 9/18                                   | [Categorical predictors](activities/L07-slr-cat-predictor.qmd)                       | [07-slr-cat-predictor-notes.qmd](template_qmds/07-slr-cat-predictor-notes.qmd)                       | Before class:                                                                                                                                     |
|                                        |                                                                                      |                                                                                                      |                                                                                                                                                   |
|                                        |                                                                                      |                                                                                                      | -   [CP 5](https://moodle.macalester.edu/mod/quiz/view.php?id=208944)                                                                             |
|                                        |                                                                                      |                                                                                                      |                                                                                                                                                   |
|                                        |                                                                                      |                                                                                                      | Due tonight:                                                                                                                                      |
|                                        |                                                                                      |                                                                                                      |                                                                                                                                                   |
|                                        |                                                                                      |                                                                                                      | -   PP 2                                                                                                                                          |
+----------------------------------------+--------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------+
| **Unit 2: Multiple Linear Regression** |                                                                                      |                                                                                                      |                                                                                                                                                   |
+----------------------------------------+--------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------+
| 9/23                                   | [Multiple linear regression discovery day](activities/L08-mlr-intro.qmd)             | [08-mlr-intro-notes.qmd](template_qmds/08-mlr-intro-notes.qmd)                                       |                                                                                                                                                   |
+----------------------------------------+--------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------+
| 9/25                                   | **Quiz 1**                                                                           |                                                                                                      |                                                                                                                                                   |
+----------------------------------------+--------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------+
| 9/30                                   | [Modeling principles](activities/L09-mlr-principles.qmd)                             | [09-mlr-principles-notes.qmd](template_qmds/09-mlr-principles-notes.qmd)                             | [CP 6](https://moodle.macalester.edu/mod/quiz/view.php?id=208947)                                                                                 |
+----------------------------------------+--------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------+
| 10/2                                   | [Confounding](activities/L10-mlr-confounding.qmd)                                    | [10-mlr-confounding-notes.qmd](template_qmds/10-mlr-confounding-notes.qmd)                           | [CP 7](https://moodle.macalester.edu/mod/quiz/view.php?id=208948)                                                                                 |
+----------------------------------------+--------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------+
| 10/7                                   | [Interactions](activities/L12-mlr-interaction-practice.qmd)                          | [12-mlr-interaction-practice-notes.qmd](template_qmds/12-mlr-interaction-practice-notes.qmd)         | Before class:                                                                                                                                     |
|                                        |                                                                                      |                                                                                                      |                                                                                                                                                   |
|                                        |                                                                                      |                                                                                                      | -   [CP 8](https://moodle.macalester.edu/mod/quiz/view.php?id=208949)                                                                             |
|                                        |                                                                                      |                                                                                                      |                                                                                                                                                   |
|                                        |                                                                                      |                                                                                                      | Due tonight:                                                                                                                                      |
|                                        |                                                                                      |                                                                                                      |                                                                                                                                                   |
|                                        |                                                                                      |                                                                                                      | -   PP 3                                                                                                                                          |
+----------------------------------------+--------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------+
| 10/9                                   | [Model building](activities/L13-mlr-model-building-1.qmd)                            | [13-mlr-model-building-1-notes.qmd](template_qmds/13-mlr-model-building-1-notes.qmd)                 | Before class:                                                                                                                                     |
|                                        |                                                                                      |                                                                                                      |                                                                                                                                                   |
|                                        |                                                                                      |                                                                                                      | -   [CP 9](https://moodle.macalester.edu/mod/quiz/view.php?id=208950)                                                                             |
|                                        |                                                                                      |                                                                                                      |                                                                                                                                                   |
|                                        |                                                                                      |                                                                                                      | Beginning of class:                                                                                                                               |
|                                        |                                                                                      |                                                                                                      |                                                                                                                                                   |
|                                        |                                                                                      |                                                                                                      | -   Quiz 1 Revisions                                                                                                                              |
+----------------------------------------+--------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------+
| **Unit 3: Logistic Regression**        |                                                                                      |                                                                                                      |                                                                                                                                                   |
+----------------------------------------+--------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------+
| 10/14                                  | [Logistic regression I](activities/L16-logistic-univariate.qmd)                      | [16-logistic-univariate-notes.qmd](template_qmds/16-logistic-univariate-notes.qmd)                   | Before class:                                                                                                                                     |
|                                        |                                                                                      |                                                                                                      |                                                                                                                                                   |
|                                        |                                                                                      |                                                                                                      | -   [CP 10](https://moodle.macalester.edu/mod/quiz/view.php?id=208952) **AND** [CP 11](https://moodle.macalester.edu/mod/quiz/view.php?id=208953) |
|                                        |                                                                                      |                                                                                                      |                                                                                                                                                   |
|                                        |                                                                                      |                                                                                                      | Due tonight:                                                                                                                                      |
|                                        |                                                                                      |                                                                                                      |                                                                                                                                                   |
|                                        |                                                                                      |                                                                                                      | -   PP 4                                                                                                                                          |
+----------------------------------------+--------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------+
| 10/16                                  | Fall break (no class!)                                                               |                                                                                                      |                                                                                                                                                   |
+----------------------------------------+--------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------+
| 10/21                                  | [Logistic regression II](activities/L17-logistic-multiple-evaluation.qmd)            | [17-logistic-multiple-evaluation-notes.qmd](template_qmds/17-logistic-multiple-evaluation-notes.qmd) | Before class:                                                                                                                                     |
|                                        |                                                                                      |                                                                                                      |                                                                                                                                                   |
|                                        |                                                                                      |                                                                                                      | -   [CP 12](https://moodle.macalester.edu/mod/quiz/view.php?id=208954)                                                                            |
+----------------------------------------+--------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------+
| 10/23                                  | Review + project time                                                                |                                                                                                      | Due tonight:                                                                                                                                      |
|                                        |                                                                                      |                                                                                                      |                                                                                                                                                   |
|                                        |                                                                                      |                                                                                                      | -   PP 5                                                                                                                                          |
+----------------------------------------+--------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------+
| **Unit 4: Inference**                  |                                                                                      |                                                                                                      |                                                                                                                                                   |
+----------------------------------------+--------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------+
| 10/28                                  | [Tools for inference](activities/L18-sampling-normal.qmd)                            | [18-sampling-normal-notes.qmd](template_qmds/18-sampling-normal-notes.qmd)                           | Before class:                                                                                                                                     |
|                                        |                                                                                      |                                                                                                      |                                                                                                                                                   |
|                                        |                                                                                      |                                                                                                      | -   [CP 13](https://moodle.macalester.edu/mod/quiz/view.php?id=208956)                                                                            |
+----------------------------------------+--------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------+
| 10/30                                  | **Quiz 2**                                                                           |                                                                                                      |                                                                                                                                                   |
+----------------------------------------+--------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------+
| 11/4                                   | Sampling distributions + CLT                                                         |                                                                                                      | Before class:                                                                                                                                     |
|                                        |                                                                                      |                                                                                                      |                                                                                                                                                   |
|                                        |                                                                                      |                                                                                                      | -   [CP 14](https://moodle.macalester.edu/mod/quiz/view.php?id=208957)                                                                            |
+----------------------------------------+--------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------+
| 11/6                                   | Project time                                                                         |                                                                                                      | Due tonight:                                                                                                                                      |
|                                        |                                                                                      |                                                                                                      |                                                                                                                                                   |
|                                        |                                                                                      |                                                                                                      | -   Project Milestone 1                                                                                                                           |
+----------------------------------------+--------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------+
| 11/11                                  | Confidence intervals                                                                 |                                                                                                      | CP 15                                                                                                                                             |
+----------------------------------------+--------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------+
| 11/13                                  | Towards hypothesis testing                                                           |                                                                                                      | PP 6                                                                                                                                              |
+----------------------------------------+--------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------+
| 11/18                                  | Hypothesis tests for 1 coefficient                                                   |                                                                                                      | CP 16                                                                                                                                             |
+----------------------------------------+--------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------+
| 11/20                                  | Considerations in hypothesis testing                                                 |                                                                                                      | PP 7                                                                                                                                              |
+----------------------------------------+--------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------+
| 11/25                                  | Project time                                                                         |                                                                                                      | Project Milestone 2                                                                                                                               |
+----------------------------------------+--------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------+
| 11/27                                  | Thanksgiving break                                                                   |                                                                                                      |                                                                                                                                                   |
+----------------------------------------+--------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------+
| 12/2                                   | Nested models                                                                        |                                                                                                      | CP 17                                                                                                                                             |
+----------------------------------------+--------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------+
| 12/4                                   | P-values + project time                                                              |                                                                                                      | PP 8                                                                                                                                              |
+----------------------------------------+--------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------+
| 12/9                                   | Project time                                                                         |                                                                                                      | Project final submission                                                                                                                          |
+----------------------------------------+--------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------+
| 12/16 (10:30am-12:30pm)                | **Quiz 3**                                                                           |                                                                                                      |                                                                                                                                                   |
+----------------------------------------+--------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------+

If you find any typos, bugs, dead links, or have other questions, please email [jcarls13\@macalester.edu](mailto:jcarls13@macalester.edu){.email}
