---
title: "Course Schedule"
sidebar: false
---

This page is the first place you'll want to visit at the beginning of each class. The **Topic** column will contain a link to today's activity (to follow along on the screen), and the **.qmd template** column contains a link to download a .qmd file where you can work on the exercises.

-   Details for the current week will be filled in throughout the semester. Any urgent announcements will be made over email.

-   Project-related due dates are not yet in the schedule.

-   Details are subject to change (with plenty of advance warning).

-   Unless specified otherwise:

    -   Moodle Checkpoints (CPs) are due 10 minutes before class.

    -   Practice problems (PPs) are due on Moodle by 11:59pm on the due date.

+----------------------------------------+--------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+------------------------------------------------------------------------------+
| ### Date                               | ### Topic                                                                            | ### .qmd template                                                                        | ### Due                                                                      |
|                                        |                                                                                      |                                                                                          |                                                                              |
| ###                                    |                                                                                      |                                                                                          |                                                                              |
+----------------------------------------+--------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+------------------------------------------------------------------------------+
| **Unit 1: Simple Linear Regression**   |                                                                                      |                                                                                          |                                                                              |
+----------------------------------------+--------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+------------------------------------------------------------------------------+
| 9/2                                    | [Welcome](activities/L01-foundations-welcome.qmd)                                    | [01-foundations-welcome-notes.qmd](template_qmds/01-foundations-welcome-notes.qmd)       | Before class:                                                                |
|                                        |                                                                                      |                                                                                          |                                                                              |
|                                        |                                                                                      |                                                                                          | -   Review the [course syllabus](syllabus.qmd)                               |
|                                        |                                                                                      |                                                                                          | -   Familiarize yourself with Moodle and the course website                  |
|                                        |                                                                                      |                                                                                          | -   Complete the [Introductions survey](https://forms.gle/y5gBRYimGjR4uzce8) |
|                                        |                                                                                      |                                                                                          | -   [Download R and RStudio](tech_setup.qmd)                                 |
+----------------------------------------+--------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+------------------------------------------------------------------------------+
| 9/4                                    | [Univariate visual & numerical summaries](activities/L02-foundations-univariate.qmd) | [02-foundations-univariate-notes.qmd](template_qmds/02-foundations-univariate-notes.qmd) | CP 1                                                                         |
+----------------------------------------+--------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+------------------------------------------------------------------------------+
| 9/9                                    | Simple linear regression                                                             |                                                                                          | CP 2                                                                         |
+----------------------------------------+--------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+------------------------------------------------------------------------------+
| 9/11                                   | Model evaluation                                                                     |                                                                                          | PP 1, CP 3                                                                   |
+----------------------------------------+--------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+------------------------------------------------------------------------------+
| 9/16                                   | Transformations                                                                      |                                                                                          | CP 4                                                                         |
+----------------------------------------+--------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+------------------------------------------------------------------------------+
| 9/18                                   | Categorical predictors                                                               |                                                                                          | PP 2, CP 5                                                                   |
+----------------------------------------+--------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+------------------------------------------------------------------------------+
| **Unit 2: Multiple Linear Regression** |                                                                                      |                                                                                          |                                                                              |
+----------------------------------------+--------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+------------------------------------------------------------------------------+
| 9/23                                   | Multiple linear regression discovery day                                             |                                                                                          |                                                                              |
+----------------------------------------+--------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+------------------------------------------------------------------------------+
| 9/25                                   | **Quiz 1**                                                                           |                                                                                          |                                                                              |
+----------------------------------------+--------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+------------------------------------------------------------------------------+
| 9/30                                   | Modeling principles                                                                  |                                                                                          | CP 6                                                                         |
+----------------------------------------+--------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+------------------------------------------------------------------------------+
| 10/2                                   | Confounding                                                                          |                                                                                          | PP 3, CP 7                                                                   |
+----------------------------------------+--------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+------------------------------------------------------------------------------+
| 10/7                                   | Interaction                                                                          |                                                                                          | CP 8                                                                         |
+----------------------------------------+--------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+------------------------------------------------------------------------------+
| 10/9                                   | Review + project time                                                                |                                                                                          |                                                                              |
+----------------------------------------+--------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+------------------------------------------------------------------------------+
| 10/14                                  | Model building                                                                       |                                                                                          | PP 4, CP 9                                                                   |
+----------------------------------------+--------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+------------------------------------------------------------------------------+
| 10/16                                  | Fall break (no class!)                                                               |                                                                                          |                                                                              |
+----------------------------------------+--------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+------------------------------------------------------------------------------+
| **Unit 3: Logistic Regression**        |                                                                                      |                                                                                          |                                                                              |
+----------------------------------------+--------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+------------------------------------------------------------------------------+
| 10/21                                  | Logistic regression I                                                                |                                                                                          | CP 10                                                                        |
+----------------------------------------+--------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+------------------------------------------------------------------------------+
| 10/23                                  | Logistic regression II                                                               |                                                                                          | CP 11                                                                        |
+----------------------------------------+--------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+------------------------------------------------------------------------------+
| 10/28                                  | Review + project time                                                                |                                                                                          | PP 5                                                                         |
+----------------------------------------+--------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+------------------------------------------------------------------------------+
| 10/30                                  | **Quiz 2**                                                                           |                                                                                          |                                                                              |
+----------------------------------------+--------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+------------------------------------------------------------------------------+
| **Unit 4: Inference**                  |                                                                                      |                                                                                          |                                                                              |
+----------------------------------------+--------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+------------------------------------------------------------------------------+
| 11/4                                   | Tools for inference                                                                  |                                                                                          | CP 12                                                                        |
+----------------------------------------+--------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+------------------------------------------------------------------------------+
| 11/6                                   | Sampling distributions + CLT                                                         |                                                                                          | CP 13                                                                        |
+----------------------------------------+--------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+------------------------------------------------------------------------------+
| 11/11                                  | Confidence intervals                                                                 |                                                                                          | CP 14                                                                        |
+----------------------------------------+--------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+------------------------------------------------------------------------------+
| 11/13                                  | Towards hypothesis testing                                                           |                                                                                          | PP 6                                                                         |
+----------------------------------------+--------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+------------------------------------------------------------------------------+
| 11/18                                  | Hypothesis tests for 1 coefficient                                                   |                                                                                          | CP 15                                                                        |
+----------------------------------------+--------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+------------------------------------------------------------------------------+
| 11/20                                  | Considerations in hypothesis testing                                                 |                                                                                          | PP 7                                                                         |
+----------------------------------------+--------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+------------------------------------------------------------------------------+
| 11/25                                  | F tests                                                                              |                                                                                          | CP 16                                                                        |
+----------------------------------------+--------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+------------------------------------------------------------------------------+
| 11/27                                  | Thanksgiving break                                                                   |                                                                                          |                                                                              |
+----------------------------------------+--------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+------------------------------------------------------------------------------+
| 12/2                                   | P-values + project time                                                              |                                                                                          |                                                                              |
+----------------------------------------+--------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+------------------------------------------------------------------------------+
| 12/4                                   | Project time                                                                         |                                                                                          | PP 8                                                                         |
+----------------------------------------+--------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+------------------------------------------------------------------------------+
| 12/9                                   | Project time                                                                         |                                                                                          |                                                                              |
+----------------------------------------+--------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+------------------------------------------------------------------------------+
| 12/16 (10:30am-12:30pm)                | **Quiz 3**                                                                           |                                                                                          |                                                                              |
+----------------------------------------+--------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+------------------------------------------------------------------------------+
